
sudo: false
language: python
python:
  - "2.7"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run python -m unittest discover -s CrystalMatch -t CrystalMatch
  - x=$(pwd) PYTHONPATH="$PATH:$x/CrystalMatch:$x" PATH="$PATH:$x/CrystalMatch"pipenv run  python -m unittest discover -s system-tests -t system-tests -v
  - PYTHONPATH="$PATH:/home/rqq82173/PycharmProjects/CrystalMatch/CrystalMatch:/home/rqq82173/PycharmProjects/CrystalMatch" PATH="$PATH:/home/rqq82173/PycharmProjects/CrystalMatch/CrystalMatch:/home/rqq82173/PycharmProjects/CrystalMatch" pipenv run python -m unittest discover -s system-tests -t system-tests -v
